{{- if and .Values.prometheusOperatorServiceMonitor (ne .Values.deploymentType "cluster")}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ list ( include "sentinel-lily.short-instance-name" $ ) "svc-monitor" | join "-" | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "sentinel-lily.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: "metrics"
    path: "/metrics"
    interval: "30s"
{{- end }}
