---
{{- if ne .Values.deploymentType "cluster" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-lily
  labels:
    {{- include "sentinel-lily.allLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Release.Name }}-lily-daemon-service
  podManagementPolicy: {{ .Values.podManagementPolicy | default "Parallel" | quote }}
  selector:
    matchLabels:
      {{- include "sentinel-lily.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sentinel-lily.allLabels" . | nindent 8 }}
    spec:
      {{- include "sentinel-lily.common-lily-affinity-selectors" . | indent 6 }}
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: init-datastore
        image: {{ include "sentinel-lily.docker-image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["/bin/sh", "-c"]
        args:
        {{- include "sentinel-lily.initialize-datastore-script" . | nindent 10 }}
        env:
        {{- include "sentinel-lily.common-envvars" . | indent 8 }}
        volumeMounts:
        {{- include "sentinel-lily.common-volume-mounts" . | indent 8 }}
        resources:
          # resources required to initialize the datastore are small
          {{- include "sentinel-lily.minimal-resources" . | indent 10 }}
      containers:
      - name: daemon
        image: {{ include "sentinel-lily.docker-image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["lily"]
        args:
        - daemon
        {{- range .Values.daemon.args }}
        - {{ . }}
        {{- end }}
        env:
        {{- include "sentinel-lily.common-envvars" . | indent 8 }}
        ports:
        - containerPort: 1234
          name: api
        - containerPort: 1347
          name: p2p
        {{- if .Values.prometheusOperatorServiceMonitor }}
        - containerPort: 9991
          name: metrics
        {{- end }}
        volumeMounts:
        {{- include "sentinel-lily.common-volume-mounts" . | indent 8 }}
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                  # lifecycle.postStart.exec.command doesn't accept args
                  # so we execute this script as a multiline string
                {{- include "sentinel-lily.common-job-start-script" . | indent 16 }}
        resources:
        {{- if .Values.daemon.resources }}
          {{- toYaml .Values.daemon.resources | nindent 10 }}
        {{- else }}
          # Required resources to run daemon lily are signficant and the below default
          # may be insufficient. Please see https://lilium.sh/software/lily/hardware/
          # for more information.
          requests:
            cpu: "16000m"
            memory: "250Gi"
          limits:
            cpu: "16000m"
            memory: "250Gi"
        {{- end }}
      {{- if .Values.debug.enabled }}
      - name: debug
        image: {{ include "sentinel-lily.docker-image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
        env:
        {{- include "sentinel-lily.common-envvars" . | indent 8 }}
        volumeMounts:
        {{- include "sentinel-lily.common-volume-mounts" . | indent 8 }}
        resources:
        {{- if .Values.debug.resources }}
          {{- toYaml .Values.debug.resources | nindent 10 }}
        {{- else }}
          # resources required to operate the daemon as a client in this debug
          # container are typically small. Increase this value if you intend to run
          # lily as a deamon to perform indexing.
          # See https://lilium.sh/software/lily/hardware/ for more info.
          {{- (include "sentinel-lily.minimal-resources" .) | indent 10 }}
        {{- end }}
      {{- end }}
      volumes:
      {{- include "sentinel-lily.volume-mounts" . | indent 6 }}
  volumeClaimTemplates:
  {{- include "sentinel-lily.volume-claim-templates" .Values.daemon.volumes.datastore | indent 2 }}
{{- end }}

