{{- if and .Values.prometheusOperatorServiceMonitor (ne .Values.deploymentType "cluster")}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ list ( include "sentinel-lily.short-instance-name" $ ) "daemon-metrics-service" | join "-" | quote }}
  labels:
    {{- include "sentinel-lily.allLabels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9991"
    prometheus.io/path: "/metrics"
spec:
  type: "ClusterIP"
  selector:
    {{- include "sentinel-lily.selectorLabels" . | nindent 4 }}
  ports:
    - name: "daemon-metrics-service"
      protocol: "TCP"
      targetPort: "daemon-metrics-port"
      port: 9991
{{- end }}
