{{- if eq .Values.deploymentType "cluster" }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ list ( include "sentinel-lily.short-instance-name" $ ) "worker-pdb" | join "-" | quote }}
  labels:
    {{- include "sentinel-lily.allLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "sentinel-lily.workerSelectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.cluster.disruptionBudget.worker | default 2 }}
{{- end }}
