{{- if and .Values.prometheusOperatorServiceMonitor (eq .Values.deploymentType "cluster")}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ list ( include "sentinel-lily.short-instance-name" $ ) "worker-metrics-service" | join "-" | quote }}
  labels:
    {{- include "sentinel-lily.workerAllLabels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9991"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    {{- include "sentinel-lily.workerSelectorLabels" . | nindent 4 }}
  ports:
    - name: "worker-metrics-service"
      protocol: "TCP"
      targetPort: "worker-metrics-port"
      port: 9991
{{- end }}
