image:
  repository: coryschwartz/lotus-gateway
  pullPolicy: IfNotPresent
  tag: mainnet-1c62d7a40

prometheusOperatorServiceMonitor: true

# set additional arguments for run
# runArgs:
# - --api-max-lookback=100h
# - --api-wait-lookback-limit=10000

ports:
  rpc: 2346

ingress:
  enabled: false
  class: nginx
  host: example.com

loadBalancer:
  enabled: false
  rpcPort: 80
  annotations: {}

deployment:
  replicas: 1

secrets:
  jwt:
    enabled: false
    secretName: ""
    token_key: ""

lotus:
  fullnodeApiMultiaddr: "/dns/lotus-gateway-backend/tcp/1234"

# set additional environment variables on the lotus-gateway
# eg:
# gatewayEnvs:
# - name: GOLOG_LOG_FMT
#   value: json
gatewayEnvs: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

additionalLabels: {}
