{{- if .Values.nodelocker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filecoin-chain-archiver.snapshots.serviceAccountName" . }}
  labels:
    {{- include "filecoin-chain-archiver.snapshots.labels" . | nindent 4 }}
  {{- with .Values.snapshots.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
