apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filecoin-chain-archiver.nodelocker.fullname" . }}
  labels:
    {{- include "filecoin-chain-archiver.nodelocker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "filecoin-chain-archiver.nodelocker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.nodelocker.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "filecoin-chain-archiver.nodelocker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "filecoin-chain-archiver.nodelocker.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-nodelocker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - filecoin-chain-archiver
          args:
            - nodelocker
            - run
          env:
          - name: FCA_LOG_LEVEL
            value: {{ .Values.nodelocker.logging.level | quote }}
          {{- if .Values.nodelocker.logging.named }}
          - name: FCA_LOG_LEVEL_NAMED
            value: {{ include "filecoin-chain-archiver.nodelocker.logLevelNamed" . | quote }}
          {{- end }}
          - name: FCA_NODELOCKER_SERVICE_LISTEN
            value: "0.0.0.0:5100"
          - name: FCA_NODELOCKER_OPERATOR_LISTEN
            value: "0.0.0.0:5101"
          {{- with .Values.nodelocker.additionalEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
          - containerPort: 5100
            name: service
            protocol: TCP
          - containerPort: 5101
            name: operator
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: operator
          readinessProbe:
            httpGet:
              path: /readiness
              port: operator
          resources:
            {{- toYaml .Values.nodelocker.resources | nindent 12 }}
      {{- with .Values.nodelocker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodelocker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodelocker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
