apiVersion: v1
kind: Service
metadata:
  name: {{ include "filecoin-chain-archiver.fullname" . }}-nodelocker
  labels:
    {{- include "filecoin-chain-archiver.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "filecoin-chain-archiver.selectorLabels" . | nindent 4 }}
  ports:
    - name: service
      protocol: TCP
      port: 5100
      targetPort: service
    - name: operator
      protocol: TCP
      port: 5101
      targetPort: operator
