apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filsnap.fullname" . }}-config
  labels:
    {{- include "filsnap.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- range .Values.snapshots.nodes }}
    [[Nodes]]
      Address = {{ . | quote }}
      TokenPath = "/secrets/token"
    {{- end }}
