---
{{- if .Values.daemon.enabled }}
{{- if or .Values.watch.enabled .Values.walk.enabled }}
  {{- fail "a visor deployment cannot enable more than one mode, please disable one" }}
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-visor
  labels:
    app: visor
    suite: sentinel
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Release.Name }}-visor-service
  selector:
    matchLabels:
      app: visor
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: visor
        suite: sentinel
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
{{- end }}
    spec:
      securityContext:
        fsGroup: 532
        runAsNonRoot: true
        runAsUser: 532
        runAsGroup: 532
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: initfs
        image: busybox
        command: ["sh", "-c"]
        args:
          - |
            mkdir -p /var/lib/visor/keystore
        volumeMounts:
        - name: repo-volume
          mountPath: /var/lib/visor
{{- if .Values.daemon.importSnapshot.enabled }}
      - name: chain-import
        image: "{{ .Values.image.repo }}:{{ required "expected image tag to be defined" .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command: ["bash", "-c"]
        args:
          - |
            if [ -f "/var/lib/visor/datastore/_imported" ]; then
              echo "Skipping import, found /var/lib/visor/datastore/_imported file."
              echo "Ensuring secrets have correct permissions."
              chmod 0600 /var/lib/visor/keystore/*
              exit 0
            fi

            echo importing snapshot from url {{ .Values.daemon.importSnapshot.url }}
            visor init --import-snapshot={{ .Values.daemon.importSnapshot.url }}
            status=$?

            if [ $status -eq 0 ]; then
              touch "/var/lib/visor/datastore/_imported"
            fi

            echo "Ensuring secrets have correct permissions."
            chmod 0600 /var/lib/visor/keystore/*

            exit $status
        env:
        - name: GOLOG_LOG_FMT
        {{- if .Values.logFormat }}
          value: {{ .Values.logFormat }}
        {{- else }}
          value: json
        {{- end }}
        - name: VISOR_REPO
          value: /var/lib/visor
        volumeMounts:
        - name: repo-volume
          mountPath: /var/lib/visor
        - name: config-volume
          mountPath: /var/lib/visor/config.toml
          subPath: config.toml
          readOnly: true
        {{- if .Values.daemon.volumes.datastore.enabled }}
        - name: datastore-volume
          mountPath: /var/lib/visor/datastore
        {{- end }}
{{- end }}
      containers:
      - name: daemon
        image: "{{ .Values.image.repo }}:{{ required "expected image tag to be defined" .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command:
        - visor
        args:
        - daemon
        env:
        - name: GOLOG_LOG_FMT
        {{- if .Values.logFormat }}
          value: {{ .Values.logFormat }}
        {{- else }}
          value: json
        {{- end }}
        {{- if .Values.logLevel }}
        - name: GOLOG_LOG_LEVEL
          value: {{ .Values.logLevel }}
        {{- end }}
        {{- if .Values.logLevelNamed }}
        - name: VISOR_LOG_LEVEL_NAMED
          value: {{ .Values.logLevelNamed }}
        {{- end }}
        - name: VISOR_REPO
          value: /var/lib/visor
        - name: VISOR_CONFIG
          value: /var/lib/visor/config.toml
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pgSecret }}
              key: password
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pgSecret }}
              key: user
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pgSecret }}
              key: host
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pgSecret }}
              key: port
        - name: PGDATABASE
        {{- if .Values.pgDatabase }}
          value: {{ .Values.pgDatabase }}
        {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pgSecret }}
              key: database
        {{- end }}
{{- range .Values.daemon.storage.postgresql }}
        - name: VISOR_STORAGE_POSTGRESQL_{{ .name | upper }}_URL
          value: "postgres://$(PGUSER):$(PGPASSWORD)@$(PGHOST):$(PGPORT)/$(PGDATABASE)?sslmode=require"
{{- end }}
        ports:
        - containerPort: 1234
          name: api
        - containerPort: 1347
          name: p2p
        - containerPort: 9991
          name: metrics
        volumeMounts:
        - name: repo-volume
          mountPath: /var/lib/visor
        - name: config-volume
          mountPath: /var/lib/visor/config.toml
          subPath: config.toml
          readOnly: true
        {{- if .Values.daemon.volumes.datastore.enabled }}
        - name: datastore-volume
          mountPath: /var/lib/visor/datastore
        {{- end }}
        {{- if .Values.daemon.jobs }}
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - |
                  echo "Waiting for api to become ready"

                  visor wait-api --timeout=60s
                  status=$?

                  if [ $status -ne 0 ]; then
                    exit $status
                  fi

                  echo "Starting jobs"

                  {{- range .Values.daemon.jobs }}
                  visor {{ .command }} {{ join " " .args }}
                  {{- end }}
        {{- end }}
{{- if .Values.debug }}
      - name: debug
        image: "{{ .Values.image.repo }}:{{ required "expected image tag to be defined" .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command: ["sh", "-c", "tail -f /dev/null"]
        env:
        - name: VISOR_REPO
          value: /var/lib/visor
        - name: VISOR_CONFIG
          value: /var/lib/visor/config.toml
{{- range .Values.daemon.storage.postgresql }}
        - name: VISOR_STORAGE_POSTGRESQL_{{ .name | upper }}_URL
          valueFrom:
            secretKeyRef:
              name: {{ .secret }}
              key: url
{{- end }}
        volumeMounts:
        - name: repo-volume
          mountPath: /var/lib/visor
        - name: config-volume
          mountPath: /var/lib/visor/config.toml
          subPath: config.toml
          readOnly: true
        {{- if .Values.daemon.volumes.datastore.enabled }}
        - name: datastore-volume
          mountPath: /var/lib/visor/datastore
        {{- end }}
{{- end }}
      volumes:
      - name: repo-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-visor-config
          items:
          - key: config.toml
            path: config.toml
  volumeClaimTemplates:
  {{- if .Values.daemon.volumes.datastore.enabled }}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: datastore-volume
    spec:
      accessModes:
      {{- range .Values.daemon.volumes.datastore.accessModes }}
      - {{ . | quote }}
      {{- end }}
      storageClassName: {{ .Values.daemon.volumes.datastore.storageClassName }}
      volumeMode: Filesystem
      resources:
        requests:
          storage: {{ .Values.daemon.volumes.datastore.size | quote }}
      {{- with .Values.daemon.volumes.datastore.dataSource }}
      dataSource:
        {{- toYaml . | nindent 10 }}
      {{- end }}
  {{- end}}
{{- end }}

