apiVersion: v1
kind: Service
metadata:
  name: {{ include "filsnap.fullname" . }}-nodelocker
  labels:
    {{- include "filsnap.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "filsnap.selectorLabels" . | nindent 4 }}
  ports:
    - name: service
      protocol: TCP
      port: 5100
      targetPort: service
    - name: operator
      protocol: TCP
      port: 5101
      targetPort: operator
