{{- if eq .Values.deploymentType "cluster" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentinel-lily.short-instance-name" $ }}-notifier-config
  labels:
    {{- include "sentinel-lily.allLabels" . | nindent 4 }}
data:
  config.toml: |
  {{- if .Values.cluster.notifier.configOverrideEnabled }}
    {{- .Values.cluster.notifier.configOverride | indent 4 }}
  {{- else }}
    {{- include "sentinel-lily.notifier-config" . | nindent 4 }}
  {{- end }}
{{- end }}
