{{- if and .Values.prometheusOperatorServiceMonitor (eq .Values.deploymentType "cluster")}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ list ( include "sentinel-lily.short-instance-name" $ ) "notifier-metrics" | join "-" | quote }}
  labels:
    {{- include "sentinel-lily.notifierAllLabels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9991"
    prometheus.io/path: "/metrics"
spec:
  type: "ClusterIP"
  selector:
    {{- include "sentinel-lily.notifierSelectorLabels" . | nindent 4 }}
  ports:
    - protocol: "TCP"
      port: 9991
      targetPort: 9991
      name: "metrics"
{{- end }}
