{{ if .Values.controller.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dealbot-controller-metrics
  labels:
    app: visor
    release: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8764"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  selector:
      app: dealbot-controller
      release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8764
      targetPort: 8764
      name: metrics
{{ end }}

{{ if .Values.daemon.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dealbot-daemon-metrics
  labels:
    app: visor
    release: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8764"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  selector:
      app: dealbot-worker
      release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8764
      targetPort: 8764
      name: metrics
{{ end }}
