{{- if .Values.application.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.application.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.application.name }}
    release: {{ .Release.Name }}
    {{- with .Values.application.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.application.service.type }}
  selector:
    app: {{ .Values.application.name }}
    release: {{ .Release.Name }}
  ports:
    {{- with .Values.application.service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- range $i, $svc := .Values.application.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $.Values.application.name }}-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Values.application.name }}
    release: {{ $.Release.Name }}
    {{- with $.Values.application.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- toYaml $svc | nindent 2 }} 
{{- end }}
