{{- if eq .Values.deploymentType "cluster" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ list ( include "sentinel-lily.short-instance-name" $ ) "redis-main" | join "-" | quote }}
  labels:
    app: "redis"
spec:
  selector:
    matchLabels:
      app: "redis"
      role: "main"
  replicas: 1
  template:
    metadata:
      labels:
        app: "redis"
        role: "main"
    spec:
      containers:
      - name: "main"
        image: "redis"
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
        ports:
        - containerPort: 6379
{{- end }}
