# Default values for fil-sentinel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
pgPoolSize: 45
logLevel: info
image:
  repo: filecoin/sentinel-visor
  tag: master-latest
  pullPolicy: IfNotPresent
# lotus api multiaddr
# if unset uses default value of:
# /dns/{{ .Release.Name }}-lotus-daemon.{{ .Release.Namespace }}.svc.cluster.local/tcp/1234
lotusAPIMultiaddr: ""
# a lotus-fullnode secret containing jwt token under key jwt-ro-privs-token
# secret must be in the same namespace
# if unset uses default value of:
# {{ .Release.Name }}-jwt-secrets
lotusAPITokenSecret: ""
# postgresql database
# if left empty, a database will be created with the following convention:
# <namespace>-<release>-sentinel
database: ""
# prometheus service monitor
prometheusOperatorServiceMonitor: false

#
# Args
#
allowAutomaticMigration: true

tasks:
  indexLatest:
    enabled: true
    cacheLength: 25
  indexHistory:
    enabled: true
  processTipSets:
    workers: 15
    batch: 10
    lease: "15m"
  processActors:
    workers: 15
    batch: 10
    lease: "15m"
#   includeActorType:
#   excludeActorType:
  processMessages:
    workers: 15
    batch: 10
    lease: "15m"
  processGasOutputs:
    workers: 15
    batch: 10
    lease: "15m"
# heightFrom: 0
# heightTo: 100

#
# Tracing
#
jaeger:
  enabled: false

resources:
  requests:
    cpu: 8000m
    memory: 32Gi
  limits:
    cpu: 16000m
    memory: 64Gi
