# Default values for fil-sentinel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
pgPoolSize: 45
# Name of a secret containing password, user, host, port and database keys for a postgres database
pgSecret: "sentinel-monitoring-postgresql-secrets"
pgSSLMode: "require"
logLevel: info
image:
  repo: filecoin/sentinel-visor
  tag: master-latest
  pullPolicy: IfNotPresent

# may add custom labels
# labels:
#   name: foo

# Type of lens to use: lotus, lotusrepo, carrepo, sql
lens: lotus

# Hint to pass to lens
lensCacheHint: 1048576

# lotus api multiaddr
# required if using the lotus API
lotusAPIMultiaddr: ""

# a lotus-fullnode secret containing jwt token under key jwt-ro-privs-token
# required if using the lotus API
lotusAPITokenSecret: ""

# postgresql database
# if left empty, a database will be created with the following convention:
# <namespace>-<release>-sentinel
database: ""

# prometheus service monitor
prometheusOperatorServiceMonitor: false

# The name of a VolumeSnapshot containing a lotus datastore.
# If set, the snapshot will be mounted as a read only volume under /var/lib/lotus/datastore
lotusDatastoreSnapshot: ""

# The size of the datastore snapshot, must correspond to the snapshot being used
lotusDatastoreSize: "10Gi"

# The storage class of the datastore snapshot
lotusDatastoreStorageClass: "ebs-sc"

# Path to lotus repository if not using lotus API
lotusPath: "/var/lib/lotus"


#
# Args
#
allowAutomaticMigration: true

tasks:
  indexLatest:
    enabled: true
    cacheLength: 25
  indexHistory:
    enabled: true
  processTipSets:
    workers: 2
    batch: 10
    lease: "15m"
  processActors:
    workers: 2
    batch: 10
    lease: "15m"
#   includeActorType:
#   excludeActorType:
  processMessages:
    workers: 2
    batch: 10
    lease: "15m"
  processGasOutputs:
    workers: 2
    batch: 10
    lease: "15m"
  processChainEconomics:
    workers: 2
    batch: 10
    lease: "15m"
#  heightFrom: 0
#  heightTo: 100
  # Refresh frequency for processing stats
#  processingStatsRefresh: "1m"
  # Refresh frequency for chain visualization views
#  chainvisRefresh: "15m"
  # Base time to wait between starting tasks (jitter is added)
#  taskDelay: "500ms"
#
# Tracing
#
jaeger:
  enabled: false

resources:
  requests:
    cpu: 8000m
    memory: 32Gi
  limits:
    cpu: 16000m
    memory: 64Gi
