# Default values for fil-sentinel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
pgPoolSize: 45
logLevel: info
image:
  repo: filecoin/sentinel-visor
  tag: master-latest
  pullPolicy: IfNotPresent
# lotus api multiaddr
# if unset uses default value of:
# /dns/{{ .Release.Name }}-lotus-daemon.{{ .Release.Namespace }}.svc.cluster.local/tcp/1234
lotusAPIMultiaddr: ""
# postgresql database
# if left empty, a database will be created with the following convention:
# <namespace>-<release>-sentinel
database: ""
# prometheus service monitor
prometheusOperatorServiceMonitor: false
# tracing
jaeger:
  enabled: false
resources:
  requests:
    cpu: 8000m
    memory: 32Gi
  limits:
    cpu: 16000m
    memory: 64Gi
