# Default values for sentinel-visor
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
logLevel: info
image:
  repo: filecoin/sentinel-visor
  tag: "v0.5.3" # required
  pullPolicy: IfNotPresent

# Custom labels
#labels:
  #name: foo

#
# Global
#

# PostgreSQL options
pgSecret: "" # required
pgDatabase: "" # default `database` key from pgSecret
pgSSLMode: "require"
pgPoolSize: 45
pgAppName: "" # default: "visor_<version>_<host>_<runtime_pid>"

# Debug Options

# sleep container without exiting
debug: false

# prometheus service monitor
prometheusOperatorServiceMonitor: false
prometheusPort: ":9991"

logLevel: error
#logFormat: json
#logLevelNamed: "vm:error,badgerbs:error"

jaeger:
  enabled: false
  host: ""
  port: 6831
  serviceName: "" # default: "visor"
  sampler:
    type: "probabilistic"
    param: 0.0001


allowAutomaticMigration: true

lens: # configure how visor sources its data
  lotusAPI: # backed by a live node's API
    # a lotus-fullnode secret containing jwt read-only token under key 'jwt-ro-privs-token'
    # secret must be in the same namespace
    lotusAPITokenSecret: "" # default: "{{ .Release.Name }}-jwt-secrets"
    # lotus api multiaddr
    lotusAPIMultiaddr: "" # required

#
# Mode-specific
#
watch:
  enabled: true
  confidence: 1
  tasks:
    - blocks
    - messages
    - chaineconomics
    # for least confusion during runtime, pick only one actorStates task. (last one applies)
    - actorstatesraw
    #- actorstatesparsed
    #- actorstatesboth
walk:
  enabled: false
  #from: 0 # default: 0
  #to: 1000 # default: host's MaxUint64
  tasks:
    - blocks
    - messages
    - chaineconomics
    # for least confusion during runtime, pick only one actorStates task. (last one applies)
    - actorstatesraw
    #- actorstatesparsed
    #- actorstatesboth

resources:
  requests:
    cpu: 8000m
    memory: 32Gi
  limits:
    cpu: 16000m
    memory: 64Gi
