{{- if .Values.prometheusOperatorServiceMonitor }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lily-daemon-metrics
  labels:
    {{- include "sentinel-lily.allLabels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9991"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  selector:
    {{- include "sentinel-lily.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 9991
      targetPort: 9991
      name: metrics
{{- end }}
