apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filecoin-chain-archiver.index-resolver.fullname" . }}
  labels:
    {{- include "filecoin-chain-archiver.index-resolver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.indexResolver.replicas }}
  selector:
    matchLabels:
      {{- include "filecoin-chain-archiver.index-resolver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.indexResolver.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "filecoin-chain-archiver.index-resolver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "filecoin-chain-archiver.index-resolver.serviceAccountName" . }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "filecoin-chain-archiver.index-resolver.fullname" . }}-config
          items:
          - key: config.toml
            path: config.toml
      - name: s3-resolver-secret-volume
        secret:
          secretName: {{ include "filecoin-chain-archiver.index-resolver.secretName" . }}
          optional: false
      containers:
        - name: {{ .Chart.Name }}-index-resolver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - filecoin-chain-archiver
          args:
            - index-resolver-service
            - run
          env:
          - name: FCA_LOG_LEVEL
            value: {{ .Values.indexResolver.logging.level | quote }}
          {{- if .Values.indexResolver.logging.named }}
          - name: FCA_LOG_LEVEL_NAMED
            value: {{ include "filecoin-chain-archiver.index-resolver.logLevelNamed" . | quote }}
          {{- end }}
          - name: FCA_INDEX_RESOLVER_SERVICE_LISTEN
            value: "0.0.0.0:5200"
          - name: FCA_INDEX_RESOLVER_OPERATOR_LISTEN
            value: "0.0.0.0:5201"
          - name: FCA_INDEX_RESOLVER_CONFIG_PATH
            value: "/config/config.toml"
          {{- with .Values.indexResolver.additionalEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
          - name: config-volume
            mountPath: /config/config.toml
            subPath: config.toml
            readOnly: true
          - name: s3-resolver-secret-volume
            mountPath: /secrets/s3
            readOnly: true
          ports:
          - containerPort: 5200
            name: service
            protocol: TCP
          - containerPort: 5201
            name: operator
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: operator
          readinessProbe:
            httpGet:
              path: /readiness
              port: operator
          resources:
            {{- toYaml .Values.indexResolver.resources | nindent 12 }}
      {{- with .Values.indexResolver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexResolver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexResolver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
