{{- if not .Values.indexResolver.s3Resolver.secretName }}
{{- $secretName := printf "%s-%s" (include "filecoin-chain-archiver.index-resolver.fullname" . ) "s3" }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filecoin-chain-archiver.index-resolver.secretName" . }}
  labels:
    {{- include "filecoin-chain-archiver.index-resolver.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.indexResolver.s3Resolver.accessKey }}
  ACCESS_KEY: {{ .Values.indexResolver.s3Resolver.accessKey | b64enc | quote }}
{{- else if $secretData.ACCESS_KEY }}
  ACCESS_KEY: {{ get $secretData "ACCESS_KEY" | quote }}
{{- end }}
{{- if .Values.indexResolver.s3Resolver.secretKey }}
  SECRET_KEY: {{ .Values.indexResolver.s3Resolver.secretKey | b64enc | quote }}
{{- else if $secretData.SECRET_KEY }}
  SECRET_KEY: {{ get $secretData "SECRET_KEY" | quote }}
{{- end }}
{{- end }}
