{{- if .Values.indexResolver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filecoin-chain-archiver.index-resolver.serviceAccountName" . }}
  labels:
    {{- include "filecoin-chain-archiver.index-resolver.labels" . | nindent 4 }}
  {{- with .Values.indexResolver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
