apiVersion: v1
kind: Service
metadata:
  name: {{ include "filecoin-chain-archiver.index-resolver.fullname" . }}
  labels:
    {{- include "filecoin-chain-archiver.index-resolver.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "filecoin-chain-archiver.index-resolver.selectorLabels" . | nindent 4 }}
  ports:
    - name: service
      protocol: TCP
      port: 5200
      targetPort: service
    - name: operator
      protocol: TCP
      port: 5201
      targetPort: operator
---
{{- if .Values.indexResolver.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "filecoin-chain-archiver.index-resolver.fullname" . }}-lb
  labels:
    {{- include "filecoin-chain-archiver.index-resolver.labels" . | nindent 4 }}
  {{- with .Values.indexResolver.loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    {{- include "filecoin-chain-archiver.index-resolver.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: service
  - name: https
    protocol: TCP
    port: 443
    targetPort: service
{{- end }}
